export const ROUTE_PATH = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    DASHBOARD: '/dashboard',
    USER_DASHBOARD: '/app',
    USER_UNITS: '/app/units',
    USER_UNIT_DETAIL: '/app/units/:unitId',
    USER_LESSONS: '/app/lessons',
    USER_LESSON_DETAIL: '/app/lessons/:lessonId',
    USER_QUIZZES: '/app/quizzes',
    USER_QUIZ: '/app/quiz/:quizId',
    USER_QUIZ_SESSION: '/app/quiz/:quizId/session/:attemptId',
    USER_PROGRESS: '/app/progress',
    USER_PROFILE: '/app/profile',
    UNAUTHORIZED: '/unauthorized',
    NOT_FOUND: '*',
    ADMIN: '/admin',
    ADMIN_DASHBOARD: '/admin/dashboard',
    ADMIN_USERS: '/admin/users',
    ADMIN_LEVELS: '/admin/levels',
    ADMIN_UNITS: '/admin/units',
    ADMIN_LESSONS: '/admin/lessons',
    ADMIN_VOCABULARIES: '/admin/vocabularies',
    ADMIN_QUIZZES: '/admin/quizzes',
    ADMIN_QUESTIONS: '/admin/questions',
    ADMIN_ROLES_PERMISSIONS: '/admin/roles-permissions',
}